sudo: required

language: go

go:
  - 1.9.x
install:
  - echo "Please don't go get"
  
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

script:
  - make build
  - make build_samples
  - ./test/version.sh ./faas-cli

# todo:
#  - ./deploy_samples.sh # requires a deployed FaaS

after_success:
    - if [ ! -z "$TRAVIS_TAG" ] ; then
        if [ -z "$DOCKER_NS" ] ; then
          export DOCKER_NS=openfaas;
        fi;

        docker tag $DOCKER_NS/faas-cli:latest-dev $DOCKER_NS/faas-cli:$TRAVIS_TAG;
        echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin;
        docker push $DOCKER_NS/faas-cli:$TRAVIS_TAG;
      fi;

before_deploy:
  - make build_redist
  - ./ci/hashgen.sh

deploy:
  provider: releases
  api_key:
      secure: "ccc2EHUfLvOyVPGOBCMyWLfKVbB5lLMJOcC/kZOmMZ89jJ373fBbIrrr6RV4S1NXpJMRb4YcZkINnwugLeArLNy7/8tzfev14Vg9/e2oNR5v8JW0grPkl9POazAoD4w6eIJmeeq6PZ9RkNt4DtSvDY4TjSJ728UoaTcgnnmM3+fM3KfzMMSxmjohAWGytbqzZ+qxy9HxNbOmAE183D+N9ftSPLwDbK9ImZCHzLCBBea3HB6pAj9vTmMN5TNy+TzFolXON+UzG8rImX/3Tavv3+bDwD6iAsvAKv5kCTn4fjPa3jIdHr+GOv0xPnmSAv71/t6xewZVa3+xxGQUEzh1HftWI6XcaRZTcRjh4+ntksSLx0ZGRV3O6xppx7M1kKnSP0/7JHfZB+tLAaESoot22vJPLFdT5xfRhBtBVOJbW2p4PCwkdhgSMi93UFhSFRSOj8RhG0kyvO65rYHGJYw3LDfzMDd3ZMMHILdV5T1Sr3IXyp7FziQ9lIsk67zOzNgZXcRUibrh5cBy+qApB6JkHjQyOfmnK2TDNXQM89/Yzzfsrf9dZSK954UUV5hckzlcbvNDmBO/v9GHLhE1t+S6nEE8+lAyeSA5zz8juFwQ5eJl40ebOTLSzml0n+wwAFd4BxmqqkUnZeBE9mwAbCf7tpoxQV7o8YKFCKW5zKhMsPY="
  file: 
  - faas-cli
  - faas-cli-darwin
  - faas-cli-armhf
  - faas-cli.exe
  - faas-cli-arm64
  - faas-cli.sha256
  - faas-cli-darwin.sha256
  - faas-cli-armhf.sha256
  - faas-cli.exe.sha256
  - faas-cli-arm64.sha256
  skip_cleanup: true
  on:
    tags: true
